apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.releaseName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
 
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.releaseName }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            command:
            - /bin/sh
            - -c
            - |
              echo "Running cron job {{ .Values.releaseName }} with version {{ .Values.image.tag }} at $(date)" > /output/{{ .Values.outputPath }}/file-$(date +\%Y\%m\%dT\%H\%M\%S).txt
            env:
            - name: OUTPUT_PATH
              value: "{{ .Values.outputPath }}"
            volumeMounts:
            - name: output-volume
              mountPath: /output
          restartPolicy: OnFailure
          volumes:
          - name: output-volume
            persistentVolumeClaim:
              claimName: {{ .Values.persistentVolumeClaim.name }}
