apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-v1
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cronjob-v1
    meta.helm.sh/release-namespace: cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-v1
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            command:
            - /bin/sh
            - -c
            - |
              echo "Running CronJob v1 at $(date)" > /output/file-$(date +%Y%m%dT%H%M%S).txt
            env:
            - name: OUTPUT_PATH
              value: "{{ .Values.outputPath }}"
            volumeMounts:
            - name: output-volume
              mountPath: /output
          restartPolicy: OnFailure
          volumes:
          - name: output-volume
            persistentVolumeClaim:
              claimName: {{ .Values.persistentVolumeClaim.name }}
