apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Values.cronJobs.name }}
  namespace: cronjob
  labels:
    app: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.cronJobs.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cronJobs.name }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            command:
            - /bin/sh
            - -c
            - |
              echo "Running cron job {{ .Values.cronJobs.name }} with version {{ .Values.image.tag }} at $(date)" > /output/{{ .Values.cronJobs.outputPath }}/file-$(date +\%Y\%m\%dT\%H\%M\%S).txt
            env:
            - name: OUTPUT_PATH
              value: "{{ .Values.cronJobs.outputPath }}"
            volumeMounts:
            - name: output-volume
              mountPath: /output
          restartPolicy: OnFailure
          volumes:
          - name: output-volume
            persistentVolumeClaim:
              claimName: {{ .Values.persistentVolumeClaim.name }}
