{{- range .Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: "{{ $.Release.Name }}"
    meta.helm.sh/release-namespace: "{{ $.Values.namespace }}"
spec:
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
            command:
            - /bin/sh
            - -c
            - |
              echo "Running cron job {{ .name }} with version {{ $.Values.image.tag }} at $(date)" > /output/{{ .outputPath }}/file-$(date +\%Y\%m\%dT\%H\%M\%S).txt
            env:
            - name: OUTPUT_PATH
              value: "{{ .outputPath }}"
            volumeMounts:
            - name: output-volume
              mountPath: /output
          restartPolicy: OnFailure
          volumes:
          - name: output-volume
            persistentVolumeClaim:
              claimName: {{ $.Values.persistentVolumeClaim.name }}
{{- end }}
