apiVersion: v1
kind: Namespace
metadata:
  name: cronjob
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cronjob-app
    meta.helm.sh/release-namespace: cronjob
