apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: cronjob
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
