{{- range .Values.cronJobs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.persistentVolumeClaim.name }}
  namespace: {{ .namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
