pipeline {
    agent any
    parameters {
        string(name: 'VERSION', defaultValue: 'latest', description: 'Docker image version')
    }
    environment {
        REGISTRY = 'prasoonshrama25'
        IMAGE = 'cronjob-app'
        TAG = "${params.VERSION}" // Use the version parameter for tagging
        DOCKER_CREDENTIALS_ID = 'docker-credentials-id'
        KUBE_CONFIG = credentials('kubeconfig')
    }
    stages {
        stage('Install Helm') {
            steps {
                script {
                    bat '''
                        echo Installing Helm...

                        :: Download Helm installation script
                        curl -fsSL -o get_helm.bat https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

                        :: Make the script executable
                        chmod 700 get_helm.bat

                        :: Run the script to install Helm
                        get_helm.bat

                        :: Clean up the installation script
                        del get_helm.bat

                        :: Verify Helm installation
                        helm version
                    '''
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image with the specified version
                    bat "docker build -t ${REGISTRY}/${IMAGE}:${params.VERSION} -f Dockerfile ."
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Push Docker image to the registry with the specified tag
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        bat "docker push ${REGISTRY}/${IMAGE}:${params.VERSION}"
                    }
                }
            }
        }
        stage('Deploy CronJob Version 1') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        bat '''
                            helm upgrade --install cronjob-app-v1 ./helm/cronjob-multi-version \
                            --namespace cronjob --create-namespace \
                            --set image.repository=${REGISTRY}/${IMAGE} \
                            --set image.tag=${VERSION} \
                            --set cronJob.name=cronjob-v1 \
                            --set cronJob.schedule="*/5 * * * *" \
                            --set cronJob.outputPath=logs/version1
                        '''
                    }
                }
            }
        }
        stage('Deploy CronJob Version 2') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        bat '''
                            helm upgrade --install cronjob-app-v2 ./helm/cronjob-multi-version \
                            --namespace cronjob \
                            --set image.repository=${REGISTRY}/${IMAGE} \
                            --set image.tag=${VERSION} \
                            --set cronJob.name=cronjob-v2 \
                            --set cronJob.schedule="*/10 * * * *" \
                            --set cronJob.outputPath=logs/version2
                        '''
                    }
                }
            }
        }
        stage('Deploy CronJob Version 3') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        bat '''
                            helm upgrade --install cronjob-app-v3 ./helm/cronjob-multi-version \
                            --namespace cronjob \
                            --set image.repository=${REGISTRY}/${IMAGE} \
                            --set image.tag=${VERSION} \
                            --set cronJob.name=cronjob-v3 \
                            --set cronJob.schedule="*/15 * * * *" \
                            --set cronJob.outputPath=logs/version3
                        '''
                    }
                }
            }
        }
    }
}
